publish:
  docker:
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    file: Dockerfile.arm
    repo: easypi/shadowsocks-libev-arm
    tag:
      - latest
      - 2.4.8
