server:
  image: easypi/shadowsocks-libev
  ports:
    - "8388:8388/tcp"
    - "8388:8388/udp"
  environment:
    - METHOD=chacha20-ietf-poly1305
    - PASSWORD=5ouMnqPyzseL
  restart: always

client:
  image: easypi/shadowsocks-libev
  command:
    ss-local -s 1.2.3.4
             -p 8388
             -m chacha20-ietf-poly1305
             -k 5ouMnqPyzseL
             -b 0.0.0.0
             -l 1080
             -t 60
             --fast-open
  ports:
    - "1080:1080"
  restart: always

client-arm:
  image: easypi/shadowsocks-libev-arm
  ports:
    - "1080:1080"
  environment:
    - SERVER_ADDR=1.2.3.4
    - METHOD=chacha20-ietf-poly1305
    - PASSWORD=5ouMnqPyzseL
  restart: always

server-arm64:
  image: dengrenjie31/shadowsocks-libev-arm64
  ports:
    - "8388:8388/tcp"
    - "8388:8388/udp"
  environment:
    - METHOD=chacha20-ietf-poly1305
    - PASSWORD=5ouMnqPyzseL
  restart: always

client-arm64:
  image: dengrenjie31/shadowsocks-libev-arm64
  command:
    ss-local -s 1.2.3.4
             -p 8388
             -m chacha20-ietf-poly1305
             -k 5ouMnqPyzseL
             -b 0.0.0.0
             -l 1080
             -t 60
             --fast-open
  ports:
    - "1080:1080"
  restart: always
