server:
  image: easypi/shadowsocks-libev
  ports:
    - "8388:8388/tcp"
    - "8388:8388/udp"
  environment:
    - PASSWORD=5ouMnqPyzseL
  restart: always

client:
  image: easypi/shadowsocks-libev-arm
  ports:
    - "1080:1080"
  environment:
    - SERVER_ADDR=1.2.3.4
    - PASSWORD=5ouMnqPyzseL
  restart: always
